Repository guibranco/progressbar, pull requests merged in 2024-10, with the labels that each got.

#45 Enhance SVG styling with square style and template management
  README.md
  app.py
  templates/progress.svg
Labels: documentation, enhancement, help wanted, good first issue, hacktoberfest, Review effort [1-5]: 3

#47 Update README.md for clarity on style parameter
  README.md
Labels: documentation, Review effort [1-5]: 1

#50 Added the Plastic Style
  README.md
  app.py
  templates/progress.svg
Labels: 📝 documentation, enhancement, help wanted, good first issue, hacktoberfest
