Repository guibranco/progressbar, pull requests merged in 2025-03, with the labels that each got.

#91 Explore/codebase
  README.md
  app.py
Labels: enhancement, 🚦 awaiting triage, documentation, bug fix, Review effort [1-5]: 4

#93 Create dependabot.yml
  .github/dependabot.yml
Labels: enhancement, ☑️ auto-merge

#94 Create CONTRIBUTING.md
  CONTRIBUTING.md
Labels: ☑️ auto-merge, Review effort [1-5]: 2, documentation

#96 Update README.md
  README.md
Labels: ☑️ auto-merge, Review effort [1-5]: 2, documentation

#97 Create contributors-readme.yml
  .github/workflows/contributors-readme.yml
Labels: enhancement, ☑️ auto-merge, Review effort [1-5]: 2

#98 Create infisical-secrets-check.yml
  .github/workflows/infisical-secrets-check.yml
Labels: enhancement, ☑️ auto-merge, Review effort [1-5]: 2

#100 Create GitVersion.yml
  GitVersion.yml
Labels: enhancement, ☑️ auto-merge, Review effort [1-5]: 1

#99 Create size-label.yml
  .github/workflows/size-label.yml
Labels: enhancement, ☑️ auto-merge, Review effort [1-5]: 2, size/S

#101 Create ci.yml
  .github/workflows/ci.yml
Labels: enhancement, ☑️ auto-merge, Review effort [1-5]: 2, size/M

#106 Update LICENSE +semver; major
  LICENSE
Labels: enhancement, ☑️ auto-merge, size/XS

#105 Update README.md
  README.md
Labels: ☑️ auto-merge, Review effort [1-5]: 2, size/M, documentation

#108 Create build.yml
  .github/workflows/build.yml
  test_api.py
Labels: enhancement, ☑️ auto-merge, Review effort [1-5]: 2, size/M

#109 Update ci.yml +semver: minor
  .github/workflows/ci.yml
Labels: enhancement, ☑️ auto-merge, Review effort [1-5]: 2, size/S

#110 feat - add new styles and githooks for the project
  .githooks/pre-commit
  .githooks/prepare-commit-msg
  app.py
Labels: enhancement, ☑️ auto-merge, size/L, Review effort [1-5]: 4, Other

#113 Revert "feat - add new styles and githooks for the project"
  .githooks/pre-commit
  .githooks/prepare-commit-msg
  app.py
Labels: enhancement, ☑️ auto-merge, Review effort [1-5]: 2, size/L, bug fix

#125 Update README.md
  README.md
Labels: ☑️ auto-merge, Review effort [1-5]: 1, size/XS, documentation
